# ==================
# AUTH
# ==================

{
  "Authorization": "Bearer YOUR_TOKEN_HERE"
}

# Register
mutation Register {
  register(input: { email: "admin@test.com", password: "123456", role: "ADMIN" }) {
    token
    message
  }
}

# Login
mutation Login {
  login(input: { email: "admin@test.com", password: "123456" }) {
    token
    message
  }
}

# ==================
# VEHICLES
# ==================

# Add Vehicle
mutation AddVehicle {
  addVehicle(input: { plate: "TUN-001", type: "car", owner_id: 1 }) {
    id
    plate
    type
    owner_id
  }
}

# Get All Vehicles
query GetVehicles {
  vehicles {
    id
    plate
    type
    owner_id
  }
}

# Get One Vehicle
query GetVehicle {
  vehicle(id: 1) {
    id
    plate
    type
    owner_id
  }
}

# Add GPS Position
mutation AddGps {
  addGpsPosition(vehicle_id: 1, input: { latitude: 36.8065, longitude: 10.1815 }) {
    id
    latitude
    longitude
    vehicle_id
    recorded_at
  }
}

# Get Vehicle History
query GetHistory {
  vehicleHistory(vehicle_id: 1) {
    id
    latitude
    longitude
    vehicle_id
    recorded_at
  }
}

# ==================
# TRAFFIC
# ==================

# Create Zone
mutation CreateZone {
  createZone(input: { name: "Centre Ville" }) {
    id
    name
    density
    level
  }
}

# Get All Zones
query GetZones {
  zones {
    id
    name
    density
    level
  }
}

# Get Congested Zones
query GetCongestedZones {
  congestedZones {
    id
    name
    density
    level
  }
}

# Update Density
mutation UpdateDensity {
  updateDensity(id: 1, input: { density: 55.5 }) {
    id
    name
    density
    level
  }
}

# ==================
# INCIDENTS
# ==================

# Create Incident
mutation CreateIncident {
  createIncident(input: { type: ACCIDENT, description: "Car crash on main road", latitude: 36.8065, longitude: 10.1815, reported_by: 1 }) {
    id
    type
    status
    description
    latitude
    longitude
  }
}

# Get All Incidents
query GetIncidents {
  incidents {
    id
    type
    status
    description
    latitude
    longitude
  }
}

# Get One Incident
query GetIncident {
  incident(id: 1) {
    id
    type
    status
    description
    latitude
    longitude
  }
}

# Update Incident Status
mutation UpdateIncidentStatus {
  updateIncidentStatus(id: 1, input: { status: EN_COURS }) {
    id
    type
    status
    description
  }
}

# ==================
# NOTIFICATIONS
# ==================

# Send Notification
mutation SendNotification {
  sendNotification(input: { user_id: 1, message: "New incident reported near you" }) {
    id
    user_id
    message
    is_read
  }
}

# Get User Notifications
query GetNotifications {
  notifications(user_id: 1) {
    id
    user_id
    message
    is_read
  }
}

# Mark As Read
mutation MarkAsRead {
  markNotificationRead(id: 1) {
    id
    user_id
    message
    is_read
  }
}